import test from 'node:test';import assert from 'node:assert/strict';
import { QueueManager,type QueueItem } from '../src/queue-manager.js';import { commandEffect,type ContentResolver, type RadioCommand } from '../src/commands.js';
const at='2026-09-01T00:00:00Z';
function item(id:string,source:QueueItem['source']='AUTO',priority:QueueItem['priority']='NORMAL',policy:QueueItem['interruptPolicy']='FINISH_CURRENT',sequence=0):QueueItem{return{id,mediaId:`media-${id}`,title:id,path:`/${id}.m4a`,durationSeconds:20,source,priority,interruptPolicy:policy,intendedAt:at,createdAt:at,sequence};}
test('default playlist loops and fallback activates only when AUTO is empty',()=>{const q=new QueueManager([item('a'),item('b')],item('fallback','FALLBACK','LOW'));assert.equal(q.next(true)?.item.id,'a');assert.equal(q.next(true)?.item.id,'b');assert.equal(q.next(true)?.item.id,'a');assert.equal(new QueueManager([],item('fallback','FALLBACK','LOW')).next(true)?.item.id,'fallback');});
test('priority and stable source ordering are explicit',()=>{const q=new QueueManager([],item('fallback','FALLBACK','LOW'));q.enqueue(item('normal-schedule','SCHEDULED','NORMAL'));q.enqueue(item('high-schedule','SCHEDULED','HIGH'));q.enqueue(item('high-manual','MANUAL','HIGH'));assert.equal(q.next(true)?.item.id,'high-manual');assert.equal(q.next(true)?.item.id,'high-schedule');assert.equal(q.next(true)?.item.id,'normal-schedule');});
test('PLAY_NEXT waits while INTERRUPT preempts current without overlap semantics',()=>{const q=new QueueManager([item('auto')],item('fallback','FALLBACK','LOW'));q.next(true);q.enqueue(item('next','MANUAL','NORMAL','PLAY_NEXT'));assert.equal(q.next(false),null);assert.equal(q.next(true)?.item.id,'next');q.enqueue(item('interrupt','MANUAL','HIGH','INTERRUPT'));const decision=q.next(false);assert.equal(decision?.item.id,'interrupt');assert.equal(decision?.interruptCurrent,true);});
test('STOP_AFTER_CURRENT and RESUME_AUTO are reversible operator intent',()=>{const q=new QueueManager([item('a')],item('fallback','FALLBACK','LOW'));q.next(true);q.requestStopAfterCurrent();assert.equal(q.next(true),null);q.resumeAuto();assert.equal(q.next(true)?.item.id,'a');});
test('duplicate queue mutation is idempotent',()=>{const q=new QueueManager([],item('fallback','FALLBACK','LOW'));q.enqueue(item('same','MANUAL'));q.enqueue(item('same','MANUAL'));assert.equal(q.snapshot().pending.length,1);});
test('command payloads produce deterministic effects and reject ambiguous content',async()=>{const resolver:ContentResolver={resolveMedia:async id=>({mediaId:id,title:id,path:`/${id}.m4a`,durationSeconds:20}),resolvePlaylist:async id=>[{mediaId:`${id}-1`,title:'one',path:'/one.m4a',durationSeconds:20},{mediaId:`${id}-2`,title:'two',path:'/two.m4a',durationSeconds:20}]};const command:RadioCommand={id:'cmd',stationId:'station',type:'PLAY_NEXT',priority:'NORMAL',payload:{playlist_id:'list'},createdAt:at};const effect=await commandEffect(command,resolver);assert.equal(effect.kind,'ENQUEUE');if(effect.kind==='ENQUEUE'){assert.equal(effect.items.length,2);assert.deepEqual(effect.items.map(x=>x.sequence),[0,1]);assert.ok(effect.items.every(x=>x.interruptPolicy==='PLAY_NEXT'));}await assert.rejects(()=>commandEffect({...command,payload:{media_id:'m',playlist_id:'p'}},resolver),/exactly one/);});
test('live commands remain deliberately deferred',async()=>{const resolver={} as ContentResolver;await assert.rejects(()=>commandEffect({id:'cmd',stationId:'s',type:'START_LIVE',priority:'LIVE',payload:{},createdAt:at},resolver),/deferred/);});
test('SKIP, STOP_AFTER_CURRENT and RESUME_AUTO map to explicit effects',async()=>{const resolver={} as ContentResolver;for(const [type,kind] of [['SKIP','SKIP'],['STOP_AFTER_CURRENT','STOP_AFTER_CURRENT'],['RESUME_AUTO','RESUME_AUTO']] as const){assert.deepEqual(await commandEffect({id:type,stationId:'s',type,priority:'NORMAL',payload:{},createdAt:at},resolver),{kind});}});
