import test from 'node:test';import assert from 'node:assert/strict';import { mkdtemp,writeFile,rm } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join } from 'node:path';
import { buildLiquidsoapScript,redact } from '../src/source.js';import type { Config } from '../src/config.js';import { loadAndValidatePlaylist } from '../src/playlist.js';

const base={stationId:'00000000-0000-0000-0000-000000000001',ownerId:'test',databaseMode:'disabled',ffmpegPath:'ffmpeg',ffprobePath:'ffprobe',liquidsoapPath:'liquidsoap',liquidsoapAllowRoot:false,icecastHost:'127.0.0.1',icecastPort:8000,mount:'/tarteel.mp3',sourceUser:'source',sourcePassword:'top secret',playlistPath:'/tmp/p.json',fallbackPath:'/tmp/f.wav',workspaceRoot:'/tmp/tarteel',healthPort:8091,leaseSeconds:15,heartbeatSeconds:5,sourceTimeoutSeconds:20,restartMax:5,version:'test',schedulerPollSeconds:5,commandPollSeconds:2,missedGraceSeconds:120,queueLookaheadSeconds:120,liquidsoapControlPort:1234,faultInjectionEnabled:false} satisfies Config;
test('liquidsoap config uses request queue, loopback control, playout ACK and fixed live profile',()=>{const script=buildLiquidsoapScript(base,"/tmp/a\"; system(\"touch PWNED\");\"");assert.match(script,/%mp3\(bitrate=128, samplerate=44100, stereo=true\)/);assert.ok(script.includes('mount="/tarteel.mp3"'));assert.ok(script.includes('settings.server.telnet.bind_addr := "127.0.0.1"'));assert.ok(script.includes('request.queue(id="automation")'));assert.ok(script.includes('radio.on_track(track_started)'));assert.ok(script.includes('TARTEEL_EVENT TRACK_START'));assert.doesNotMatch(script,/system\("touch PWNED"\)/);});
test('source URLs and credentials are redacted',()=>{
  assert.equal(redact('failed icecast://source:secret@127.0.0.1:8000/tarteel.mp3'),'failed icecast://[REDACTED]@127.0.0.1:8000/tarteel.mp3');
  assert.equal(redact('authorization=Basic-secret password=hunter2'),'authorization=[REDACTED] password=[REDACTED]');
});
test('invalid track is skipped and valid fallback is selected',async()=>{const dir=await mkdtemp(join(tmpdir(),'tarteel-radio-test-'));try{const bad=join(dir,'bad.mp3');const fallback=join(dir,'fallback.wav');const manifest=join(dir,'playlist.json');await writeFile(bad,'not audio');const {spawnSync}=await import('node:child_process');const generated=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-f','lavfi','-i','sine=frequency=440:duration=0.5','-y',fallback]);assert.equal(generated.status,0);await writeFile(manifest,JSON.stringify({tracks:[{title:'bad',path:bad}]}));const result=await loadAndValidatePlaylist(manifest,fallback,'ffprobe');assert.equal(result.fallbackUsed,true);assert.equal(result.tracks.length,1);assert.equal(result.failed.length,1);}finally{await rm(dir,{recursive:true,force:true});}});
